apiVersion: v1
kind: Template
metadata:
  name: "nginx-example"
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: "test"
  data:
    config: |-
      test1
      test2
  path: /configs
